//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/ModelView/Client/MonoBehaviour/World/Input/GameInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ET
{
    public partial class @GameInputAction: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInputAction()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputAction"",
    ""maps"": [
        {
            ""name"": ""SuperSoda"",
            ""id"": ""571434dc-d57c-435d-87f7-a63cb07073e8"",
            ""actions"": [
                {
                    ""name"": ""AddCoin"",
                    ""type"": ""Button"",
                    ""id"": ""080b0555-c51a-4181-9203-0368c983424f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""3998d27e-2b7d-41da-a995-17571d01c8d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncBet"",
                    ""type"": ""Button"",
                    ""id"": ""d7fb67c8-b43d-4737-8a89-444370a4933b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Auto"",
                    ""type"": ""Button"",
                    ""id"": ""06a84c5e-1408-4ff1-85cf-1f41a11805a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ticket"",
                    ""type"": ""Button"",
                    ""id"": ""263efdf8-cbb3-4f3a-ae06-766eb2a0b2f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSetting"",
                    ""type"": ""Button"",
                    ""id"": ""45f21c44-f23d-4be0-93e8-23548396444f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestRun"",
                    ""type"": ""Button"",
                    ""id"": ""87f30205-2946-4b24-9d69-b7a65dc4f3e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""001572f7-594c-47a2-9acf-f109e81e5aeb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""504b614c-bf7c-4eba-8236-c7541f41fd1a"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e95c34b8-f24a-475b-b2cb-903681a24878"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b444083-928e-426d-8299-2dec0ffe8a5b"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af23d1e6-f3d8-4e95-af24-9da52bd58fd2"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6da19605-2e5f-4328-a742-b23ec7f3107d"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5ba6a86-62ca-4b8d-abaa-b39011fe8a59"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ticket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ecb92a-b981-4b01-800a-cdb74925cf23"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ticket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6df07a76-9c93-4bc3-92d6-2fa3cfe989d6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSetting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9148a70-c2d3-48b2-aa18-8d778ca01361"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSetting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee2df6fb-4b95-4a91-8ca8-b632cf57daa8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncBet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b62786f9-7b8b-44da-8aa0-7f4328f294fe"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncBet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15128817-4681-4e58-91ce-fd8cf2fa5da0"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5596fd6-7ae2-44da-8387-89f194a2475d"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CoinPusher"",
            ""id"": ""46a1465d-189c-4a14-814e-e548881709e0"",
            ""actions"": [
                {
                    ""name"": ""AddCoin"",
                    ""type"": ""Button"",
                    ""id"": ""76fe3210-9324-4125-a40a-545bed0b7822"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn"",
                    ""type"": ""Button"",
                    ""id"": ""b503bec7-edb5-45db-8f10-01905c096a16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wiper"",
                    ""type"": ""Button"",
                    ""id"": ""9fc693e2-6b79-4033-9422-b835dceb33ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddManyCoin"",
                    ""type"": ""Button"",
                    ""id"": ""98dab12a-3675-41e5-8997-66e75a237df6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Auto"",
                    ""type"": ""Button"",
                    ""id"": ""1387cd7d-f192-42c9-ab74-0a2d250e7315"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PusherData"",
                    ""type"": ""Button"",
                    ""id"": ""709bc629-c3d3-44a1-af0f-b610262b1238"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle"",
                    ""type"": ""Button"",
                    ""id"": ""294dca7b-8802-4f05-bf58-2e5f9543524c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""47f32b2a-6126-4e07-8cd5-a435d914c53c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wiper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd4c9c6d-12fd-4819-bbae-ef935cffed7a"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wiper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b2e8c18-c129-4575-a29f-721d21bd78da"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6391fbd5-3db7-472d-ac3a-9ef15f45df17"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f51fbdc-a1dd-44e7-bc98-5d4e627807bb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49769fa3-0276-4fd4-991e-73e707eeee25"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""823125a8-0c4b-4342-b378-e377ec004322"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eddaaa0a-0ac3-40ea-96a8-568fb7d75fab"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""665906ae-ab17-4c05-992b-625c4324c4da"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddManyCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2894c691-fe79-4994-ae1c-48a8d93218fc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherData"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44d47629-cb33-49be-b0c6-7b0d8c1a3354"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherData"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""c7107635-a215-4044-9ab2-09231107e0b5"",
            ""actions"": [
                {
                    ""name"": ""Scale"",
                    ""type"": ""Value"",
                    ""id"": ""b1c1303d-f15a-4efb-b060-960ecd61ea08"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6a1f00c8-a156-4b6b-86cf-644982d2622c"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // SuperSoda
            m_SuperSoda = asset.FindActionMap("SuperSoda", throwIfNotFound: true);
            m_SuperSoda_AddCoin = m_SuperSoda.FindAction("AddCoin", throwIfNotFound: true);
            m_SuperSoda_Start = m_SuperSoda.FindAction("Start", throwIfNotFound: true);
            m_SuperSoda_IncBet = m_SuperSoda.FindAction("IncBet", throwIfNotFound: true);
            m_SuperSoda_Auto = m_SuperSoda.FindAction("Auto", throwIfNotFound: true);
            m_SuperSoda_Ticket = m_SuperSoda.FindAction("Ticket", throwIfNotFound: true);
            m_SuperSoda_OpenSetting = m_SuperSoda.FindAction("OpenSetting", throwIfNotFound: true);
            m_SuperSoda_TestRun = m_SuperSoda.FindAction("TestRun", throwIfNotFound: true);
            // CoinPusher
            m_CoinPusher = asset.FindActionMap("CoinPusher", throwIfNotFound: true);
            m_CoinPusher_AddCoin = m_CoinPusher.FindAction("AddCoin", throwIfNotFound: true);
            m_CoinPusher_Spawn = m_CoinPusher.FindAction("Spawn", throwIfNotFound: true);
            m_CoinPusher_Wiper = m_CoinPusher.FindAction("Wiper", throwIfNotFound: true);
            m_CoinPusher_AddManyCoin = m_CoinPusher.FindAction("AddManyCoin", throwIfNotFound: true);
            m_CoinPusher_Auto = m_CoinPusher.FindAction("Auto", throwIfNotFound: true);
            m_CoinPusher_PusherData = m_CoinPusher.FindAction("PusherData", throwIfNotFound: true);
            m_CoinPusher_Cycle = m_CoinPusher.FindAction("Cycle", throwIfNotFound: true);
            // Camera
            m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
            m_Camera_Scale = m_Camera.FindAction("Scale", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // SuperSoda
        private readonly InputActionMap m_SuperSoda;
        private List<ISuperSodaActions> m_SuperSodaActionsCallbackInterfaces = new List<ISuperSodaActions>();
        private readonly InputAction m_SuperSoda_AddCoin;
        private readonly InputAction m_SuperSoda_Start;
        private readonly InputAction m_SuperSoda_IncBet;
        private readonly InputAction m_SuperSoda_Auto;
        private readonly InputAction m_SuperSoda_Ticket;
        private readonly InputAction m_SuperSoda_OpenSetting;
        private readonly InputAction m_SuperSoda_TestRun;
        public struct SuperSodaActions
        {
            private @GameInputAction m_Wrapper;
            public SuperSodaActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @AddCoin => m_Wrapper.m_SuperSoda_AddCoin;
            public InputAction @Start => m_Wrapper.m_SuperSoda_Start;
            public InputAction @IncBet => m_Wrapper.m_SuperSoda_IncBet;
            public InputAction @Auto => m_Wrapper.m_SuperSoda_Auto;
            public InputAction @Ticket => m_Wrapper.m_SuperSoda_Ticket;
            public InputAction @OpenSetting => m_Wrapper.m_SuperSoda_OpenSetting;
            public InputAction @TestRun => m_Wrapper.m_SuperSoda_TestRun;
            public InputActionMap Get() { return m_Wrapper.m_SuperSoda; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SuperSodaActions set) { return set.Get(); }
            public void AddCallbacks(ISuperSodaActions instance)
            {
                if (instance == null || m_Wrapper.m_SuperSodaActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SuperSodaActionsCallbackInterfaces.Add(instance);
                @AddCoin.started += instance.OnAddCoin;
                @AddCoin.performed += instance.OnAddCoin;
                @AddCoin.canceled += instance.OnAddCoin;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @IncBet.started += instance.OnIncBet;
                @IncBet.performed += instance.OnIncBet;
                @IncBet.canceled += instance.OnIncBet;
                @Auto.started += instance.OnAuto;
                @Auto.performed += instance.OnAuto;
                @Auto.canceled += instance.OnAuto;
                @Ticket.started += instance.OnTicket;
                @Ticket.performed += instance.OnTicket;
                @Ticket.canceled += instance.OnTicket;
                @OpenSetting.started += instance.OnOpenSetting;
                @OpenSetting.performed += instance.OnOpenSetting;
                @OpenSetting.canceled += instance.OnOpenSetting;
                @TestRun.started += instance.OnTestRun;
                @TestRun.performed += instance.OnTestRun;
                @TestRun.canceled += instance.OnTestRun;
            }

            private void UnregisterCallbacks(ISuperSodaActions instance)
            {
                @AddCoin.started -= instance.OnAddCoin;
                @AddCoin.performed -= instance.OnAddCoin;
                @AddCoin.canceled -= instance.OnAddCoin;
                @Start.started -= instance.OnStart;
                @Start.performed -= instance.OnStart;
                @Start.canceled -= instance.OnStart;
                @IncBet.started -= instance.OnIncBet;
                @IncBet.performed -= instance.OnIncBet;
                @IncBet.canceled -= instance.OnIncBet;
                @Auto.started -= instance.OnAuto;
                @Auto.performed -= instance.OnAuto;
                @Auto.canceled -= instance.OnAuto;
                @Ticket.started -= instance.OnTicket;
                @Ticket.performed -= instance.OnTicket;
                @Ticket.canceled -= instance.OnTicket;
                @OpenSetting.started -= instance.OnOpenSetting;
                @OpenSetting.performed -= instance.OnOpenSetting;
                @OpenSetting.canceled -= instance.OnOpenSetting;
                @TestRun.started -= instance.OnTestRun;
                @TestRun.performed -= instance.OnTestRun;
                @TestRun.canceled -= instance.OnTestRun;
            }

            public void RemoveCallbacks(ISuperSodaActions instance)
            {
                if (m_Wrapper.m_SuperSodaActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISuperSodaActions instance)
            {
                foreach (var item in m_Wrapper.m_SuperSodaActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SuperSodaActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SuperSodaActions @SuperSoda => new SuperSodaActions(this);

        // CoinPusher
        private readonly InputActionMap m_CoinPusher;
        private List<ICoinPusherActions> m_CoinPusherActionsCallbackInterfaces = new List<ICoinPusherActions>();
        private readonly InputAction m_CoinPusher_AddCoin;
        private readonly InputAction m_CoinPusher_Spawn;
        private readonly InputAction m_CoinPusher_Wiper;
        private readonly InputAction m_CoinPusher_AddManyCoin;
        private readonly InputAction m_CoinPusher_Auto;
        private readonly InputAction m_CoinPusher_PusherData;
        private readonly InputAction m_CoinPusher_Cycle;
        public struct CoinPusherActions
        {
            private @GameInputAction m_Wrapper;
            public CoinPusherActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @AddCoin => m_Wrapper.m_CoinPusher_AddCoin;
            public InputAction @Spawn => m_Wrapper.m_CoinPusher_Spawn;
            public InputAction @Wiper => m_Wrapper.m_CoinPusher_Wiper;
            public InputAction @AddManyCoin => m_Wrapper.m_CoinPusher_AddManyCoin;
            public InputAction @Auto => m_Wrapper.m_CoinPusher_Auto;
            public InputAction @PusherData => m_Wrapper.m_CoinPusher_PusherData;
            public InputAction @Cycle => m_Wrapper.m_CoinPusher_Cycle;
            public InputActionMap Get() { return m_Wrapper.m_CoinPusher; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CoinPusherActions set) { return set.Get(); }
            public void AddCallbacks(ICoinPusherActions instance)
            {
                if (instance == null || m_Wrapper.m_CoinPusherActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CoinPusherActionsCallbackInterfaces.Add(instance);
                @AddCoin.started += instance.OnAddCoin;
                @AddCoin.performed += instance.OnAddCoin;
                @AddCoin.canceled += instance.OnAddCoin;
                @Spawn.started += instance.OnSpawn;
                @Spawn.performed += instance.OnSpawn;
                @Spawn.canceled += instance.OnSpawn;
                @Wiper.started += instance.OnWiper;
                @Wiper.performed += instance.OnWiper;
                @Wiper.canceled += instance.OnWiper;
                @AddManyCoin.started += instance.OnAddManyCoin;
                @AddManyCoin.performed += instance.OnAddManyCoin;
                @AddManyCoin.canceled += instance.OnAddManyCoin;
                @Auto.started += instance.OnAuto;
                @Auto.performed += instance.OnAuto;
                @Auto.canceled += instance.OnAuto;
                @PusherData.started += instance.OnPusherData;
                @PusherData.performed += instance.OnPusherData;
                @PusherData.canceled += instance.OnPusherData;
                @Cycle.started += instance.OnCycle;
                @Cycle.performed += instance.OnCycle;
                @Cycle.canceled += instance.OnCycle;
            }

            private void UnregisterCallbacks(ICoinPusherActions instance)
            {
                @AddCoin.started -= instance.OnAddCoin;
                @AddCoin.performed -= instance.OnAddCoin;
                @AddCoin.canceled -= instance.OnAddCoin;
                @Spawn.started -= instance.OnSpawn;
                @Spawn.performed -= instance.OnSpawn;
                @Spawn.canceled -= instance.OnSpawn;
                @Wiper.started -= instance.OnWiper;
                @Wiper.performed -= instance.OnWiper;
                @Wiper.canceled -= instance.OnWiper;
                @AddManyCoin.started -= instance.OnAddManyCoin;
                @AddManyCoin.performed -= instance.OnAddManyCoin;
                @AddManyCoin.canceled -= instance.OnAddManyCoin;
                @Auto.started -= instance.OnAuto;
                @Auto.performed -= instance.OnAuto;
                @Auto.canceled -= instance.OnAuto;
                @PusherData.started -= instance.OnPusherData;
                @PusherData.performed -= instance.OnPusherData;
                @PusherData.canceled -= instance.OnPusherData;
                @Cycle.started -= instance.OnCycle;
                @Cycle.performed -= instance.OnCycle;
                @Cycle.canceled -= instance.OnCycle;
            }

            public void RemoveCallbacks(ICoinPusherActions instance)
            {
                if (m_Wrapper.m_CoinPusherActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICoinPusherActions instance)
            {
                foreach (var item in m_Wrapper.m_CoinPusherActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CoinPusherActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CoinPusherActions @CoinPusher => new CoinPusherActions(this);

        // Camera
        private readonly InputActionMap m_Camera;
        private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
        private readonly InputAction m_Camera_Scale;
        public struct CameraActions
        {
            private @GameInputAction m_Wrapper;
            public CameraActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @Scale => m_Wrapper.m_Camera_Scale;
            public InputActionMap Get() { return m_Wrapper.m_Camera; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
            public void AddCallbacks(ICameraActions instance)
            {
                if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
                @Scale.started += instance.OnScale;
                @Scale.performed += instance.OnScale;
                @Scale.canceled += instance.OnScale;
            }

            private void UnregisterCallbacks(ICameraActions instance)
            {
                @Scale.started -= instance.OnScale;
                @Scale.performed -= instance.OnScale;
                @Scale.canceled -= instance.OnScale;
            }

            public void RemoveCallbacks(ICameraActions instance)
            {
                if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICameraActions instance)
            {
                foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CameraActions @Camera => new CameraActions(this);
        public interface ISuperSodaActions
        {
            void OnAddCoin(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
            void OnIncBet(InputAction.CallbackContext context);
            void OnAuto(InputAction.CallbackContext context);
            void OnTicket(InputAction.CallbackContext context);
            void OnOpenSetting(InputAction.CallbackContext context);
            void OnTestRun(InputAction.CallbackContext context);
        }
        public interface ICoinPusherActions
        {
            void OnAddCoin(InputAction.CallbackContext context);
            void OnSpawn(InputAction.CallbackContext context);
            void OnWiper(InputAction.CallbackContext context);
            void OnAddManyCoin(InputAction.CallbackContext context);
            void OnAuto(InputAction.CallbackContext context);
            void OnPusherData(InputAction.CallbackContext context);
            void OnCycle(InputAction.CallbackContext context);
        }
        public interface ICameraActions
        {
            void OnScale(InputAction.CallbackContext context);
        }
    }
}
